.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. fixedcoin_qt test_fixedcoin_qt
clean: FORCE
	$(MAKE) -C .. fixedcoin_qt_clean test_fixedcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_fixedcoin_qt_check
fixedcoin-qt fixedcoin-qt.exe: FORCE
	 $(MAKE) -C .. fixedcoin_qt
apk: FORCE
	$(MAKE) -C .. fixedcoin_qt_apk
